# Generated by Django 4.0.4 on 2022-07-23 03:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todotodo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('friend1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_sender', to=settings.AUTH_USER_MODEL)),
                ('friend2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_receiver', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='persona',
            new_name='persona_id',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='persona_message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='author',
        ),
        migrations.RemoveField(
            model_name='category',
            name='content',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='author',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='persona_name',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#DDDDDD', max_length=7),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='persona',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todo',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='todo',
            name='sender_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todo',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='TodoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(default='', max_length=256)),
                ('todo_start_date', models.DateField(default=django.utils.timezone.now)),
                ('todo_end_date', models.DateField(blank=True, null=True)),
                ('status', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reciever_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='todo_sender', to=settings.AUTH_USER_MODEL)),
                ('todo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todotodo.todo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('friends', models.ManyToManyField(related_name='friendship', through='todotodo.Friendship', to='todotodo.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonaPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('friendship_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todotodo.friendship')),
                ('persona_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todotodo.persona')),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('friend1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_sender', to=settings.AUTH_USER_MODEL)),
                ('friend2_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_receiver', to=settings.AUTH_USER_MODEL)),
                ('persona1_ids', models.ManyToManyField(related_name='sender_persona_open', to='todotodo.persona')),
                ('persona2_ids', models.ManyToManyField(related_name='receiver_persona_open', to='todotodo.persona')),
            ],
        ),
    ]
