# Generated by Django 4.0.6 on 2022-07-28 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todotodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todorequest',
            name='receiver',
            field=models.ForeignKey(default=dict, on_delete=django.db.models.deletion.CASCADE, related_name='todo_receiver_persona', to='todotodo.persona'),
        ),
    ]
