# Generated by Django 4.0.6 on 2022-07-24 07:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todotodo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todorequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='todorequest',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
