# Generated by Django 4.0.4 on 2022-07-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user'),
        ('todotodo', '0002_rename_reciever_id_todorequest_receiver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='friend1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_sender', to='accounts.kakaouser'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='friend2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_receiver', to='accounts.kakaouser'),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='friend1_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_request_sender', to='accounts.kakaouser'),
        ),
        migrations.AlterField(
            model_name='friendshiprequest',
            name='friend2_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_request_receiver', to='accounts.kakaouser'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='user_id',
            field=models.ForeignKey(default=dict, on_delete=django.db.models.deletion.CASCADE, to='accounts.kakaouser'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='sender_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.kakaouser'),
        ),
        migrations.AlterField(
            model_name='todorequest',
            name='receiver_id',
            field=models.ForeignKey(default=dict, on_delete=django.db.models.deletion.CASCADE, related_name='todo_receiver', to='accounts.kakaouser'),
        ),
        migrations.AlterField(
            model_name='todorequest',
            name='sender_id',
            field=models.ForeignKey(default=dict, on_delete=django.db.models.deletion.CASCADE, related_name='todo_sender', to='accounts.kakaouser'),
        ),
    ]
