# Generated by Django 4.0.4 on 2022-07-24 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todotodo', '0002_todorequest_created_at_todorequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todorequest',
            name='reciever_id',
            field=models.ForeignKey(default=dict, on_delete=django.db.models.deletion.CASCADE, related_name='todo_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todorequest',
            name='sender_id',
            field=models.ForeignKey(default=dict, on_delete=django.db.models.deletion.CASCADE, related_name='todo_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todorequest',
            name='todo_name',
            field=models.CharField(max_length=256),
        ),
    ]
