# Generated by Django 4.0.6 on 2022-07-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todotodo', '0002_alter_todo_sender_alter_todorequest_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todorequest',
            old_name='receiver',
            new_name='receiver_persona',
        ),
    ]
