# Generated by Django 4.0.4 on 2022-07-23 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todotodo', '0002_friendship_rename_persona_category_persona_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
