# Generated by Django 4.0.4 on 2022-07-25 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todotodo', '0003_alter_todorequest_reciever_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='user_id',
            field=models.ForeignKey(default=dict, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
