# Generated by Django 4.0.6 on 2022-07-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todotodo', '0003_rename_receiver_todorequest_receiver_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
